/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelo;

import Modelo.Agenda;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel
 */
public class UI extends javax.swing.JFrame {

    Agenda agenda = new Agenda();
    DefaultTableModel model;
    Hilo e = new Hilo();

    /**
     * Creates new form UI
     */
    public UI() {
        //e.start();

        this.setUndecorated(true);
        initComponents();

        setLocationRelativeTo(null);
        accesoTxt(false);
        btnAgregar.setEnabled(false);
        btnAceptMod.setEnabled(false);
        btnAceptMod.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBusqueda = new javax.swing.JPanel();
        txtBusqueda = new java.awt.TextField();
        btnBusqueda = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        pnlContacto = new javax.swing.JPanel();
        lblApellido = new javax.swing.JLabel();
        lblAlias = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtNombre = new java.awt.TextField();
        txtApellido = new java.awt.TextField();
        txtAlias = new java.awt.TextField();
        txtEmail = new java.awt.TextField();
        txtTelefono = new java.awt.TextField();
        btnValidarMail = new javax.swing.JButton();
        btnValidarTel = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnAceptMod = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlTable = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        pnlTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblCantContactos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDON");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setText("Busqueda");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        lblBuscar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblBuscar.setText("Buscar");
        lblBuscar.setToolTipText("");

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusqueda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 240, 80));

        lblApellido.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblApellido.setText("Apellido");

        lblAlias.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblAlias.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAlias.setText("Alias");

        lblMail.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMail.setText("E-mail");

        lblTelefono.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelefono.setText("Telefono");

        lblNombre.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNombre.setText("Nombre");

        lblTitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Contacto");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAliasActionPerformed(evt);
            }
        });
        txtAlias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAliasKeyTyped(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnValidarMail.setText("Validar Email.");
        btnValidarMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarMailActionPerformed(evt);
            }
        });

        btnValidarTel.setText("Validar Tel.");
        btnValidarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarTelActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAceptMod.setText("AceptarMod");
        btnAceptMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptModActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContactoLayout = new javax.swing.GroupLayout(pnlContacto);
        pnlContacto.setLayout(pnlContactoLayout);
        pnlContactoLayout.setHorizontalGroup(
            pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlias)
                    .addComponent(lblApellido)
                    .addComponent(lblMail)
                    .addComponent(lblTelefono)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContactoLayout.createSequentialGroup()
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValidarTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlContactoLayout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValidarMail, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(pnlContactoLayout.createSequentialGroup()
                                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContactoLayout.createSequentialGroup()
                                        .addComponent(btnAceptMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))
                                    .addGroup(pnlContactoLayout.createSequentialGroup()
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactoLayout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
            .addGroup(pnlContactoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContactoLayout.setVerticalGroup(
            pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlContactoLayout.createSequentialGroup()
                                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlContactoLayout.createSequentialGroup()
                                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNombre)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNuevo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlContactoLayout.createSequentialGroup()
                                                .addComponent(lblApellido)
                                                .addGap(10, 10, 10))
                                            .addComponent(btnAceptMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContactoLayout.createSequentialGroup()
                                        .addComponent(lblAlias)
                                        .addGap(10, 10, 10))
                                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblMail))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidarMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTelefono)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnValidarTel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnNuevo.getAccessibleContext().setAccessibleName("btnNuevo");

        getContentPane().add(pnlContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Alias", "Email", "Telefono"
            }
        ));
        tblContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContactosMouseClicked(evt);
            }
        });
        pnlTable.setViewportView(tblContactos);
        if (tblContactos.getColumnModel().getColumnCount() > 0) {
            tblContactos.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblContactos.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblContactos.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        getContentPane().add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 770, 180));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("AGENDA");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 450, 60));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.MatteBorder(null));
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.setActionCommand("");
        btnBorrar.setBorder(new javax.swing.border.MatteBorder(null));
        btnBorrar.setName("btnBorrar"); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.setBorder(new javax.swing.border.MatteBorder(null));
        btnMostrarTodos.setName("btnMostrarTodos"); // NOI18N
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAgregar.setName("btnAgregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 150, 160));
        getContentPane().add(lblCantContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 40, 20));

        jLabel1.setText("Contactos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 60, 20));

        jLabel2.setText("Usted Tiene");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnValidarMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarMailActionPerformed
        //VALIDAR EMAIL
        if (ValidarEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(null, "El EMAIL ES VALIDO!!", "VALIDO", 1);
        } else {
            JOptionPane.showMessageDialog(null, "EL EMAIL NO ES VALIDO", "INVALIDO", 1);
        }


    }//GEN-LAST:event_btnValidarMailActionPerformed

    private void btnValidarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarTelActionPerformed

        if (ValidarTelefono(txtTelefono.getText())) {
            JOptionPane.showMessageDialog(null, "EL TELEFONO ES VALIDO!!!");
        } else {
            JOptionPane.showMessageDialog(null, "EL TELEFONO NO ES VALIDO", "INVALIDO", 1);
        }

    }//GEN-LAST:event_btnValidarTelActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

         int fila = tblContactos.getSelectedRow();
            if(fila>=0){
        //MODIFICAR
        if (!txtNombre.getText().isEmpty()) {
            btnAceptMod.setVisible(true);
            btnAceptMod.setEnabled(true);
            btnAgregar.setEnabled(false);
            accesoTxt(true);
        }
        }else{JOptionPane.showMessageDialog(null, "NO HA SELECCIONADO NINGUN CONTACTO PARA MODIFICAR");}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        //BORRAR
        int eleccion = JOptionPane.YES_NO_OPTION;
        int fila = tblContactos.getSelectedRow();
        if (fila >= 0) {
            String contacto = (String) tblContactos.getValueAt(fila, 0);           
            if (JOptionPane.showConfirmDialog(null, "Esta seguro que quiere borrar a:  "+ txtNombre.getText()+" ?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            agenda.eliminar(contacto);
            agenda.mostrarTodos();
            tblContactos.setModel(agenda.model);
            limpiarTxt();
            JOptionPane.showMessageDialog(null, "EL CONTACTO FUE BORRADO"+txtNombre.getText()+""+txtApellido.getText()+" CORRECTAMENTE");
            }else{JOptionPane.showMessageDialog(null, "EL CONTACTO "+ txtNombre.getText()+" SAFO DE SER BORRADO");}
        } else {
            JOptionPane.showMessageDialog(null, "No selecciono ningun contacto");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        //MOSTRAR TODOS
        agenda.mostrarTodos();
        tblContactos.setModel(agenda.model);
        lblCantContactos.setText(Integer.toString(agenda.contarTodos()));
        e.detenerHilo();


    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //AGREGAR

        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String alias = txtAlias.getText();
        String email = txtEmail.getText();
        String telefono = txtTelefono.getText();

        if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtAlias.getText().isEmpty() || txtEmail.getText().isEmpty() || txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta algun campo");
        } else {
            Contacto cd = new Contacto(nombre, apellido, alias, email, telefono);
            cd.toString();
            agenda.agregar(cd);
            agenda.mostrarTodos();
            lblCantContactos.setText(Integer.toString(agenda.contarTodos()));
            tblContactos.setModel(agenda.model);
            limpiarTxt();
            btnAgregar.setEnabled(false);
            btnBorrar.setEnabled(true);
            btnModificar.setEnabled(true);
            JOptionPane.showMessageDialog(null, "EL CONTACTO FUE AGREGADO CON EXITO");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        e.detenerHilo();
        System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContactosMouseClicked
        accesoTxt(false);
        int fila = tblContactos.getSelectedRow();
        String id = (String) tblContactos.getValueAt(fila, 0);
        String nombre = (String) tblContactos.getValueAt(fila, 1);
        String apellido = (String) tblContactos.getValueAt(fila, 2);
        String alias = (String) tblContactos.getValueAt(fila, 3);
        String email = (String) tblContactos.getValueAt(fila, 4);
        String telefono = (String) tblContactos.getValueAt(fila, 5);

        int iduno = Integer.parseInt(id);
        Contacto mod = new Contacto(iduno, nombre, apellido, alias, email, telefono);
        System.out.println(mod.toString());

        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtAlias.setText(alias);
        txtEmail.setText(email);
        txtTelefono.setText(telefono);


    }//GEN-LAST:event_tblContactosMouseClicked

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        //Busqueda
        String contactoBuscar = txtBusqueda.getText();

        System.out.println("Estamos buscando a...: \n" + contactoBuscar + "\n");

        agenda.buscar(contactoBuscar);
        tblContactos.setModel(agenda.model);


    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtNombre.requestFocus();
        limpiarTxt();
        btnAceptMod.setVisible(false);
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        accesoTxt(true);


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped

    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliasActionPerformed

    private void txtAliasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAliasKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtAliasKeyTyped

    private void btnAceptModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptModActionPerformed
        try {
            
            int fila = tblContactos.getSelectedRow();
           
            String id = (String) tblContactos.getValueAt(fila, 0);
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String alias = txtAlias.getText();
            String email = txtEmail.getText();
            String telefono = txtTelefono.getText();

            int idUno = Integer.parseInt(id);
            Contacto mod = new Contacto(nombre, apellido, alias, email, telefono);

            agenda.modificar(mod, idUno);
            agenda.mostrarTodos();
            tblContactos.setModel(agenda.model);

            limpiarTxt();
            btnAceptMod.setVisible(false);
            accesoTxt(false);
            btnModificar.setEnabled(true);
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "algo salio mal", "ERROR", 1);

        }

    }//GEN-LAST:event_btnAceptModActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    limpiarTxt();
    accesoTxt(false);
     
        
    }//GEN-LAST:event_btnCancelActionPerformed

    //MIS METODOS----------------------------------------------------------------------
    public static Boolean ValidarTelefono(String telefono) {
        final String VALIDARTELEFONO = "^\\+?\\d{1,3}?[- .]?\\(?(?:\\d{2,3})\\)?[- .]?\\d\\d\\d[- .]?\\d\\d\\d\\d$";
        Pattern pattern = Pattern.compile(VALIDARTELEFONO);

        Matcher matcher = pattern.matcher(telefono);
        return matcher.matches();

    }
    //------------------------------------------------------------------------------------  

    public static Boolean ValidarEmail(String email) {
        final String VALIDAREMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(VALIDAREMAIL);

        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    public void accesoTxt(boolean x) {
        txtNombre.setEnabled(x);
        txtApellido.setEnabled(x);
        txtAlias.setEnabled(x);
        txtTelefono.setEnabled(x);
        txtEmail.setEnabled(x);

    }

    public void limpiarTxt() {
        if(txtNombre.getText().length() !=0){
        txtNombre.setText("");}
        if(txtApellido.getText().length() !=0){
        txtApellido.setText("");}
        if(txtAlias.getText().length() !=0){
        txtAlias.setText("");}
        if(txtTelefono.getText().length()!=0){
        txtTelefono.setText("");}
        if(txtEmail.getText().length()!=0){
        txtEmail.setText("");}

    }

    //------------------------------------------------------------------------------------  
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAceptMod;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnValidarMail;
    private javax.swing.JButton btnValidarTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAlias;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantContactos;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlContacto;
    private javax.swing.JScrollPane pnlTable;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblContactos;
    private java.awt.TextField txtAlias;
    private java.awt.TextField txtApellido;
    private java.awt.TextField txtBusqueda;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtNombre;
    private java.awt.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
